apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: micro-service
spec:
  ports:
  - name: user-edge-service-port
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: user-service-port
    port: 7911
    protocol: TCP
    targetPort: 7911
  selector:
    app: user-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: micro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 172.27.160.10:8090/micro-service/user-service:latest
        imagePullPolicy: Always
        args:
          - "--mysql.address=172.27.233.58"
        resources:
          limits:
            cpu: 1000m
            memory: 1024M
        ports:
        - containerPort: 7911
      - name: user-edge-service
        image: 172.27.160.10:8090/micro-service/user-edge-service:latest
        imagePullPolicy: Always
        args:
          - "--redis.address=172.27.233.58"
        resources:
          limits:
            cpu: 1000m
            memory: 1024M
        ports:
        - containerPort: 8082
      imagePullSecrets:
        - name: mysecret

