apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway-service
  name: api-gateway-service
  namespace: audio-deep-flow
spec:
  ports:
    - port: 8186
      protocol: TCP
      targetPort: 8186
      nodePort: 30086
  selector:
    app: api-gateway-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: audio-deep-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      serviceAccountName: audio-deep-flow-sa
      containers:
        - name: api-gateway-service
          image: registry.cn-hangzhou.aliyuncs.com/audio-deep-flow/api-gateway:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
          ports:
            - containerPort: 8186
      imagePullSecrets:
        - name: aliyunsecret

