apiVersion: v1
kind: Service
metadata:
  labels:
    app: build-model-service
  name: build-model-service
  namespace: audio-deep-flow
spec:
  ports:
    - port: 8182
      protocol: TCP
      targetPort: 8182
      nodePort: 30082
  selector:
    app: build-model-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-model-deployment
  namespace: audio-deep-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-model-service
  template:
    metadata:
      labels:
        app: build-model-service
    spec:
      containers:
        - name: build-model-service
          image: registry.cn-hangzhou.aliyuncs.com/audio-deep-flow/build-model:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "--mysql.address=172.27.233.58"
            - "--kafka.address=172.27.233.58"
            - "--docker.address=172.27.233.58"
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
          ports:
            - containerPort: 8182
        imagePullSecrets:
          - name: aliyunsecret

