apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-process-service
  name: data-process-service
  namespace: audio-deep-flow
spec:
  ports:
    - port: 8181
      protocol: TCP
      targetPort: 8181
      nodePort: 30081
  selector:
    app: data-process-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-process-deployment
  namespace: audio-deep-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-process-service
  template:
    metadata:
      labels:
        app: data-process-service
    spec:
      containers:
        - name: data-process-service
          image: registry.cn-hangzhou.aliyuncs.com/audio-deep-flow/data-process:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "--mysql.address=172.27.233.58"
            - "--kafka.address=172.27.233.58"
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
          ports:
            - containerPort: 8181
      imagePullSecrets:
        - name: aliyunsecret

