apiVersion: v1
kind: Service
metadata:
  labels:
    app: model-app-service
  name: model-app-service
  namespace: audio-deep-flow
spec:
  ports:
    - port: 8183
      protocol: TCP
      targetPort: 8183
      nodePort: 30083
  selector:
    app: model-app-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-app-deployment
  namespace: audio-deep-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-app-service
  template:
    metadata:
      labels:
        app: model-app-service
    spec:
      containers:
        - name: model-app-service
          image: registry.cn-hangzhou.aliyuncs.com/audio-deep-flow/model-app:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "--mysql.address=172.27.233.58"
            - "--kafka.address=172.27.233.58"
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
          ports:
            - containerPort: 8183
      imagePullSecrets:
        - name: aliyunsecret

