apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor-service
  name: monitor-service
  namespace: audio-deep-flow
spec:
  ports:
    - port: 8185
      protocol: TCP
      targetPort: 8185
  selector:
    app: monitor-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
  namespace: audio-deep-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-service
  template:
    metadata:
      labels:
        app: monitor-service
    spec:
      serviceAccountName: audio-deep-flow-sa
      containers:
        - name: monitor-service
          image: registry.cn-hangzhou.aliyuncs.com/audio-deep-flow/monitor-service:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "--mysql.address=172.27.233.58"
          resources:
            limits:
              cpu: 1000m
              memory: 1024M
          ports:
            - containerPort: 8185
      imagePullSecrets:
        - name: aliyunsecret

